all:
  children:

    swarm_manager:
      hosts:
        dev.diesel.net:
        
  vars:

    storage_retention: 7d

    kiwi_host: prometheus.dev.kiwi-labs.net
    diesel_host: prometheus.dev.diesel.net
    
    ansible_user: automation
    ansible_python_interpreter: /usr/bin/python3
