all:
  children:

    swarm_manager:
      hosts:
        dev.diesel.net:
        
  vars:

    storage_retention: 90d

    prom_host: prometheus.dev.kiwi-labs.net
    prom_domains_main: dev.kiwi-labs.net
    prom_domains_sans: '*.dev.kiwi-labs.net'

    ansible_user: automation
    ansible_python_interpreter: /usr/bin/python3
