all:
  children:

    swarm_manager:
      hosts:
        dev.diesel.net:
        
  vars:

    storage_retention: 90d

    prom_host: prometheus.dev.diesel.net

    ansible_user: automation
    ansible_python_interpreter: /usr/bin/python3
