all:
  children:

    swarm_manager:
      hosts:
        tools.diesel.net:
        
  vars:

    storage_retention: 1y

    kiwi_host: prometheus.kiwi-labs.net
    diesel_host: prometheus.diesel.net

    ansible_user: automation
    ansible_python_interpreter: /usr/bin/python3
