version: '3.8'
services:

  backend:
    image: prom/prometheus:v2.48.1
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
      - /etc/localtime:/etc/localtime
      - {{ config_dir }}:/etc/prometheus
      - {{ data_dir }}:/prometheus
    command: 
      - --config.file=/etc/prometheus/config.yaml 
      - --web.enable-remote-write-receiver
      - --storage.tsdb.retention.time={{ storage_retention }}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.{{ app_name }}-backend.loadbalancer.server.port=9090
        - traefik.http.middlewares.{{ app_name }}-auth.basicauth.users={{ prom_htpasswd }}

        - traefik.http.routers.kiwi-{{ app_name }}.rule=Host(`{{ kiwi_host }}`)
        - traefik.http.routers.kiwi-{{ app_name }}.middlewares={{ app_name }}-auth@docker
        - traefik.http.routers.kiwi-{{ app_name }}.tls.certresolver=cloudflare
        - traefik.http.routers.kiwi-{{ app_name }}.tls.domains[0].main={{ '.'.join( kiwi_host.split('.')[1:] ) }}
        - traefik.http.routers.kiwi-{{ app_name }}.tls.domains[0].sans=*.{{ '.'.join( kiwi_host.split('.')[1:] ) }}
        - traefik.http.routers.kiwi-{{ app_name }}.service={{ app_name }}-backend@docker

        - traefik.http.routers.diesel-{{ app_name }}.rule=Host(`{{ diesel_host }}`)
        - traefik.http.routers.diesel-{{ app_name }}.middlewares={{ app_name }}-auth@docker
        - traefik.http.routers.diesel-{{ app_name }}.tls.certresolver=step-ca
        - traefik.http.routers.diesel-{{ app_name }}.service={{ app_name }}-backend@docker
    networks:
      - {{ traefik_network }}

networks:
  {{ traefik_network }}:
    external: true
    name: {{ traefik_network }}
