- hosts: swarm_manager
  roles:
    - application
    - traefik
  tasks:

    - include_role:
        name: application
        tasks_from: make_config_dir

    - include_role:
        name: application
        tasks_from: make_data_dir

    # https://github.com/prometheus/prometheus/issues/5976
    - file:
        path: '{{ data_dir }}'
        owner: 65534
        group: 65534
        mode: u=rwx
      become: yes

    - name: 'render config.yaml to {{ config_dir}}/config.yaml'
      template:
        src: config.yaml
        dest: '{{ config_dir }}/config.yaml'
        
    - include_role:
        name: docker
        tasks_from: stack_deploy

    - include_role:
        name: docker
        tasks_from: service_update
      vars:
        options: --force
        docker_service: backend
